// Code generated by asyncapi-codegen-tools from asyncapi.yaml; DO NOT EDIT.

package apiscenario

import (
	"time"
)

const (
	EventTypeOnboardingNameSet = "onboarding_name_set"
	EventTypeOnboardingFactionSet = "onboarding_faction_set"
	EventTypePlayerOnboarded = "player_onboarded"
)

// OnboardingNameSetEvent は プレイヤーがオンボード内 name 入力ステップを完了した業務事実を表す scenario 発行イベント。
// Name は account の validate REST endpoint で事前検証済み (subscriber は再検証しない)。
// subscriber は EventID で冪等性を担保する (at-least-once)。
type OnboardingNameSetEvent struct {
	EventType string    `json:"event_type"`
	EventID   string    `json:"event_id"`
	Timestamp time.Time `json:"timestamp"`
	PlayerID  string    `json:"player_id"`
	Name      string    `json:"name"`
}

// OnboardingFactionSetEvent は プレイヤーがオンボード内 faction 選択ステップを完了した業務事実を表す scenario 発行イベント。
// InitialFactionID は SelectableFactions (overload-party-common 由来) で事前検証済み。
// subscriber は EventID で冪等性を担保する (at-least-once)。
type OnboardingFactionSetEvent struct {
	EventType        string    `json:"event_type"`
	EventID          string    `json:"event_id"`
	Timestamp        time.Time `json:"timestamp"`
	PlayerID         string    `json:"player_id"`
	InitialFactionID string    `json:"initial_faction_id"`
}

// PlayerOnboardedEvent は プレイヤーがオンボーディングシナリオを読了した業務事実 (player ごとに一度) を表す scenario 発行イベント。
// scenario.player_onboarding INSERT と同一 tx で outbox に積まれる。
// subscriber は EventID で冪等性を担保する (at-least-once)。
type PlayerOnboardedEvent struct {
	EventType        string    `json:"event_type"`
	EventID          string    `json:"event_id"`
	Timestamp        time.Time `json:"timestamp"`
	PlayerID         string    `json:"player_id"`
	InitialFactionID string    `json:"initial_faction_id"`
}

