package apiscenario

import "time"

// オンボード内 name 入力ステップ完了イベントの topic 名。
const TopicOnboardingNameSet = "onboarding-name-set"

// OnboardingNameSetEvent の EventType 値。
const EventTypeOnboardingNameSet = "onboarding_name_set"

// OnboardingNameSetEvent is published by scenario after the player completes the
// name input step of the onboarding flow. The Name field has already passed
// account's validation (via the validate REST endpoint) before publish, so
// subscribers can persist it without re-validating.
//
// Subscribers:
//
//   - account: UPDATE players.name + UPDATE players.onboarding_status='name_set'
//     in a single transaction.
//
// Idempotency: subscribers MUST dedupe on EventID via their processed_events
// table.
type OnboardingNameSetEvent struct {
	// EventType is always EventTypeOnboardingNameSet.
	EventType string `json:"event_type"`
	// EventID is a UUIDv4 generated by scenario. Idempotency key.
	EventID string `json:"event_id"`
	// Timestamp is the publisher's wall clock at enqueue time.
	Timestamp time.Time `json:"timestamp"`
	// PlayerID is the target of the name set.
	PlayerID string `json:"player_id"`
	// Name is the validated display name to persist on the player record.
	Name string `json:"name"`
}
