package apiscenario

import "time"

// オンボード内 faction 選択ステップ完了イベントの topic 名。
const TopicOnboardingFactionSet = "onboarding-faction-set"

// OnboardingFactionSetEvent の EventType 値。
const EventTypeOnboardingFactionSet = "onboarding_faction_set"

// OnboardingFactionSetEvent is published by scenario after the player selects
// their initial faction in the onboarding flow. The InitialFactionID has been
// validated against the SelectableFactions shared constant on the scenario
// side before publish.
//
// Subscribers:
//
//   - account: UPDATE players.selected_faction + INSERT player_factions
//     (source='initial_selection', ON CONFLICT DO NOTHING) +
//     UPDATE players.onboarding_status='faction_set' in a single transaction.
//
// Idempotency: subscribers MUST dedupe on EventID via their processed_events
// table.
type OnboardingFactionSetEvent struct {
	// EventType is always EventTypeOnboardingFactionSet.
	EventType string `json:"event_type"`
	// EventID is a UUIDv4 generated by scenario. Idempotency key.
	EventID string `json:"event_id"`
	// Timestamp is the publisher's wall clock at enqueue time.
	Timestamp time.Time `json:"timestamp"`
	// PlayerID is the target of the faction selection.
	PlayerID string `json:"player_id"`
	// InitialFactionID is one of SelectableFactions (SHE / Tenki / Sugar / Tuners).
	InitialFactionID string `json:"initial_faction_id"`
}
