// Package apiscenario provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apiscenario

// Defines values for LockReasonType.
const (
	LockReasonTypeEpisode LockReasonType = "episode"
	LockReasonTypeFaction LockReasonType = "faction"
	LockReasonTypeLevel   LockReasonType = "level"
)

// Valid indicates whether the value is a known member of the LockReasonType enum.
func (e LockReasonType) Valid() bool {
	switch e {
	case LockReasonTypeEpisode:
		return true
	case LockReasonTypeFaction:
		return true
	case LockReasonTypeLevel:
		return true
	default:
		return false
	}
}

// EpisodeWithStatus プレイヤー視点のエピソード 1 件 (ロック状態・進捗付き)。
// domain.Episode + UnlockContext から presenter が組み立てる wire 表現。
type EpisodeWithStatus struct {
	EpisodeID     string `json:"episode_id"`
	EpisodeNumber int64  `json:"episode_number"`

	// Faction episode が紐付くファクション (null=共通エピソード)。
	Faction     *string `json:"faction"`
	IsCompleted bool    `json:"is_completed"`
	IsUnlocked  bool    `json:"is_unlocked"`

	// LockReasons アンロック未充足の理由一覧。空配列ならアンロック済み。
	LockReasons  []LockReason `json:"lock_reasons"`
	ThumbnailURL *string      `json:"thumbnail_url"`

	// Title 要求言語に応じたタイトル。
	Title string `json:"title"`
}

// EpisodesListResponse defines model for EpisodesListResponse.
type EpisodesListResponse struct {
	Episodes []EpisodeWithStatus `json:"episodes"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// LockReason エピソードがロックされている個別理由。type ごとに有効なフィールドが決まる:
// - type=level    → required_level (整数), current_level (整数)
// - type=faction  → required_faction (faction id)
// - type=episode  → required_episode (前提エピソード id)
type LockReason struct {
	// CurrentLevel type=level のときプレイヤーの現レベル。
	CurrentLevel *int64 `json:"current_level,omitempty"`

	// RequiredEpisode type=episode のとき要求前提エピソード id。
	RequiredEpisode *string `json:"required_episode,omitempty"`

	// RequiredFaction type=faction のとき要求 faction id。
	RequiredFaction *string `json:"required_faction,omitempty"`

	// RequiredLevel type=level のとき要求レベル。
	RequiredLevel *int64 `json:"required_level,omitempty"`

	// Type ロック理由の種別 discriminator。
	Type LockReasonType `json:"type"`
}

// LockReasonType ロック理由の種別 discriminator。
type LockReasonType string

// OnboardingCompleteResponse POST /internal/v1/players/{playerId}/onboarding/complete の戻り値。
// complete request body は空 (initial faction は事前の
// POST /onboarding/faction ステップで確定済み)。
type OnboardingCompleteResponse struct {
	Message  string `json:"message"`
	PlayerID string `json:"player_id"`
}

// OnboardingFactionRequest オンボード内 faction 選択ステップの body。scenario が SelectableFactions で validate し、
// 成功時に onboarding-faction-set を outbox publish する。
type OnboardingFactionRequest struct {
	InitialFactionID string `json:"initial_faction_id"`
}

// OnboardingNameRequest オンボード内 name 入力ステップの body。scenario が account に validate を委譲し、
// 成功時に onboarding-name-set を outbox publish する。
type OnboardingNameRequest struct {
	Name string `json:"name"`
}

// OnboardingScriptResponse defines model for OnboardingScriptResponse.
type OnboardingScriptResponse struct {
	// Script オンボーディング用スクリプト本文。
	Script string `json:"script"`
}

// ScenarioCompleteResponse defines model for ScenarioCompleteResponse.
type ScenarioCompleteResponse struct {
	EpisodeID string `json:"episode_id"`
	Message   string `json:"message"`
}

// ScenarioScriptResponse defines model for ScenarioScriptResponse.
type ScenarioScriptResponse struct {
	EpisodeID string `json:"episode_id"`

	// Script GCS から読み込んだスクリプト本文 (.ks)。
	Script string `json:"script"`
}

// EpisodeIdPath defines model for EpisodeIdPath.
type EpisodeIdPath = string

// LangQuery defines model for LangQuery.
type LangQuery = string

// PlayerIdPath defines model for PlayerIdPath.
type PlayerIdPath = string

// GetOnboardingScriptParams defines parameters for GetOnboardingScript.
type GetOnboardingScriptParams struct {
	// Lang スクリプト言語 (ja / en)。未指定時は ja として扱う。
	Lang *LangQuery `form:"lang,omitempty" json:"lang,omitempty"`
}

// ListEpisodesParams defines parameters for ListEpisodes.
type ListEpisodesParams struct {
	// Lang スクリプト言語 (ja / en)。未指定時は ja として扱う。
	Lang *LangQuery `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetEpisodeScriptParams defines parameters for GetEpisodeScript.
type GetEpisodeScriptParams struct {
	// Lang スクリプト言語 (ja / en)。未指定時は ja として扱う。
	Lang *LangQuery `form:"lang,omitempty" json:"lang,omitempty"`
}

// SelectOnboardingFactionJSONRequestBody defines body for SelectOnboardingFaction for application/json ContentType.
type SelectOnboardingFactionJSONRequestBody = OnboardingFactionRequest

// UpdateOnboardingNameJSONRequestBody defines body for UpdateOnboardingName for application/json ContentType.
type UpdateOnboardingNameJSONRequestBody = OnboardingNameRequest
