// Package apiscenario provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apiscenario

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	InternalAuthScopes internalAuthContextKey = "InternalAuth.Scopes"
)

// Defines values for LockReasonType.
const (
	LockReasonTypeEpisode LockReasonType = "episode"
	LockReasonTypeFaction LockReasonType = "faction"
	LockReasonTypeLevel   LockReasonType = "level"
)

// Valid indicates whether the value is a known member of the LockReasonType enum.
func (e LockReasonType) Valid() bool {
	switch e {
	case LockReasonTypeEpisode:
		return true
	case LockReasonTypeFaction:
		return true
	case LockReasonTypeLevel:
		return true
	default:
		return false
	}
}

// EpisodeWithStatus プレイヤー視点のエピソード 1 件 (ロック状態・進捗付き)。
// domain.Episode + UnlockContext から presenter が組み立てる wire 表現。
type EpisodeWithStatus struct {
	EpisodeID     string `json:"episode_id"`
	EpisodeNumber int64  `json:"episode_number"`

	// Faction episode が紐付くファクション (null=共通エピソード)。
	Faction     *string `json:"faction"`
	IsCompleted bool    `json:"is_completed"`
	IsUnlocked  bool    `json:"is_unlocked"`

	// LockReasons アンロック未充足の理由一覧。空配列ならアンロック済み。
	LockReasons  []LockReason `json:"lock_reasons"`
	ThumbnailURL *string      `json:"thumbnail_url"`

	// Title 要求言語に応じたタイトル。
	Title string `json:"title"`
}

// EpisodesListResponse defines model for EpisodesListResponse.
type EpisodesListResponse struct {
	Episodes []EpisodeWithStatus `json:"episodes"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// LockReason エピソードがロックされている個別理由。type ごとに有効なフィールドが決まる:
// - type=level    → required_level (整数), current_level (整数)
// - type=faction  → required_faction (faction id)
// - type=episode  → required_episode (前提エピソード id)
type LockReason struct {
	// CurrentLevel type=level のときプレイヤーの現レベル。
	CurrentLevel *int64 `json:"current_level,omitempty"`

	// RequiredEpisode type=episode のとき要求前提エピソード id。
	RequiredEpisode *string `json:"required_episode,omitempty"`

	// RequiredFaction type=faction のとき要求 faction id。
	RequiredFaction *string `json:"required_faction,omitempty"`

	// RequiredLevel type=level のとき要求レベル。
	RequiredLevel *int64 `json:"required_level,omitempty"`

	// Type ロック理由の種別 discriminator。
	Type LockReasonType `json:"type"`
}

// LockReasonType ロック理由の種別 discriminator。
type LockReasonType string

// OnboardingCompleteResponse POST /api/v1/scenarios/onboarding/complete の戻り値。
// complete request body は空 (initial faction は事前の
// POST /onboarding/faction ステップで確定済み)。
type OnboardingCompleteResponse struct {
	Message  string `json:"message"`
	PlayerID string `json:"player_id"`
}

// OnboardingFactionRequest オンボード内 faction 選択ステップの body。scenario が SelectableFactions で validate し、
// 成功時に onboarding-faction-set を outbox publish する。
type OnboardingFactionRequest struct {
	InitialFactionID string `json:"initial_faction_id"`
}

// OnboardingNameRequest オンボード内 name 入力ステップの body。scenario が account に validate を委譲し、
// 成功時に onboarding-name-set を outbox publish する。
type OnboardingNameRequest struct {
	Name string `json:"name"`
}

// OnboardingScriptResponse defines model for OnboardingScriptResponse.
type OnboardingScriptResponse struct {
	// Script オンボーディング用スクリプト本文。
	Script string `json:"script"`
}

// ScenarioCompleteResponse defines model for ScenarioCompleteResponse.
type ScenarioCompleteResponse struct {
	EpisodeID string `json:"episode_id"`
	Message   string `json:"message"`
}

// ScenarioScriptResponse defines model for ScenarioScriptResponse.
type ScenarioScriptResponse struct {
	EpisodeID string `json:"episode_id"`

	// Script GCS から読み込んだスクリプト本文 (.ks)。
	Script string `json:"script"`
}

// EpisodeIdPath defines model for EpisodeIdPath.
type EpisodeIdPath = string

// LangQuery defines model for LangQuery.
type LangQuery = string

// internalAuthContextKey is the context key for InternalAuth security scheme
type internalAuthContextKey string

// ListEpisodesParams defines parameters for ListEpisodes.
type ListEpisodesParams struct {
	// Lang スクリプト言語 (ja / en)。未指定時は ja として扱う。
	Lang *LangQuery `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetEpisodeScriptParams defines parameters for GetEpisodeScript.
type GetEpisodeScriptParams struct {
	// Lang スクリプト言語 (ja / en)。未指定時は ja として扱う。
	Lang *LangQuery `form:"lang,omitempty" json:"lang,omitempty"`
}

// GetOnboardingScriptParams defines parameters for GetOnboardingScript.
type GetOnboardingScriptParams struct {
	// Lang スクリプト言語 (ja / en)。未指定時は ja として扱う。
	Lang *LangQuery `form:"lang,omitempty" json:"lang,omitempty"`
}

// SelectOnboardingFactionJSONRequestBody defines body for SelectOnboardingFaction for application/json ContentType.
type SelectOnboardingFactionJSONRequestBody = OnboardingFactionRequest

// UpdateOnboardingNameJSONRequestBody defines body for UpdateOnboardingName for application/json ContentType.
type UpdateOnboardingNameJSONRequestBody = OnboardingNameRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListEpisodes request
	ListEpisodes(ctx context.Context, params *ListEpisodesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteEpisode request
	CompleteEpisode(ctx context.Context, episodeId EpisodeIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEpisodeScript request
	GetEpisodeScript(ctx context.Context, episodeId EpisodeIdPath, params *GetEpisodeScriptParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteOnboarding request
	CompleteOnboarding(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SelectOnboardingFactionWithBody request with any body
	SelectOnboardingFactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SelectOnboardingFaction(ctx context.Context, body SelectOnboardingFactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateOnboardingNameWithBody request with any body
	UpdateOnboardingNameWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateOnboardingName(ctx context.Context, body UpdateOnboardingNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOnboardingScript request
	GetOnboardingScript(ctx context.Context, params *GetOnboardingScriptParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListEpisodes(ctx context.Context, params *ListEpisodesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEpisodesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteEpisode(ctx context.Context, episodeId EpisodeIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteEpisodeRequest(c.Server, episodeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEpisodeScript(ctx context.Context, episodeId EpisodeIdPath, params *GetEpisodeScriptParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEpisodeScriptRequest(c.Server, episodeId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteOnboarding(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteOnboardingRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SelectOnboardingFactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSelectOnboardingFactionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SelectOnboardingFaction(ctx context.Context, body SelectOnboardingFactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSelectOnboardingFactionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateOnboardingNameWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateOnboardingNameRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateOnboardingName(ctx context.Context, body UpdateOnboardingNameJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateOnboardingNameRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOnboardingScript(ctx context.Context, params *GetOnboardingScriptParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOnboardingScriptRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListEpisodesRequest generates requests for ListEpisodes
func NewListEpisodesRequest(server string, params *ListEpisodesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scenarios/episodes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Lang != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "lang", *params.Lang, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCompleteEpisodeRequest generates requests for CompleteEpisode
func NewCompleteEpisodeRequest(server string, episodeId EpisodeIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "episodeId", episodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scenarios/episodes/%s/complete", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEpisodeScriptRequest generates requests for GetEpisodeScript
func NewGetEpisodeScriptRequest(server string, episodeId EpisodeIdPath, params *GetEpisodeScriptParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "episodeId", episodeId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scenarios/episodes/%s/script", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Lang != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "lang", *params.Lang, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCompleteOnboardingRequest generates requests for CompleteOnboarding
func NewCompleteOnboardingRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scenarios/onboarding/complete")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSelectOnboardingFactionRequest calls the generic SelectOnboardingFaction builder with application/json body
func NewSelectOnboardingFactionRequest(server string, body SelectOnboardingFactionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSelectOnboardingFactionRequestWithBody(server, "application/json", bodyReader)
}

// NewSelectOnboardingFactionRequestWithBody generates requests for SelectOnboardingFaction with any type of body
func NewSelectOnboardingFactionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scenarios/onboarding/faction")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateOnboardingNameRequest calls the generic UpdateOnboardingName builder with application/json body
func NewUpdateOnboardingNameRequest(server string, body UpdateOnboardingNameJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateOnboardingNameRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateOnboardingNameRequestWithBody generates requests for UpdateOnboardingName with any type of body
func NewUpdateOnboardingNameRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scenarios/onboarding/name")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOnboardingScriptRequest generates requests for GetOnboardingScript
func NewGetOnboardingScriptRequest(server string, params *GetOnboardingScriptParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scenarios/onboarding/script")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Lang != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "lang", *params.Lang, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListEpisodesWithResponse request
	ListEpisodesWithResponse(ctx context.Context, params *ListEpisodesParams, reqEditors ...RequestEditorFn) (*ListEpisodesResponse, error)

	// CompleteEpisodeWithResponse request
	CompleteEpisodeWithResponse(ctx context.Context, episodeId EpisodeIdPath, reqEditors ...RequestEditorFn) (*CompleteEpisodeResponse, error)

	// GetEpisodeScriptWithResponse request
	GetEpisodeScriptWithResponse(ctx context.Context, episodeId EpisodeIdPath, params *GetEpisodeScriptParams, reqEditors ...RequestEditorFn) (*GetEpisodeScriptResponse, error)

	// CompleteOnboardingWithResponse request
	CompleteOnboardingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CompleteOnboardingResponse, error)

	// SelectOnboardingFactionWithBodyWithResponse request with any body
	SelectOnboardingFactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SelectOnboardingFactionResponse, error)

	SelectOnboardingFactionWithResponse(ctx context.Context, body SelectOnboardingFactionJSONRequestBody, reqEditors ...RequestEditorFn) (*SelectOnboardingFactionResponse, error)

	// UpdateOnboardingNameWithBodyWithResponse request with any body
	UpdateOnboardingNameWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOnboardingNameResponse, error)

	UpdateOnboardingNameWithResponse(ctx context.Context, body UpdateOnboardingNameJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOnboardingNameResponse, error)

	// GetOnboardingScriptWithResponse request
	GetOnboardingScriptWithResponse(ctx context.Context, params *GetOnboardingScriptParams, reqEditors ...RequestEditorFn) (*GetOnboardingScriptResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type ListEpisodesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EpisodesListResponse
}

// Status returns HTTPResponse.Status
func (r ListEpisodesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEpisodesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListEpisodesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CompleteEpisodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ScenarioCompleteResponse
}

// Status returns HTTPResponse.Status
func (r CompleteEpisodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteEpisodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CompleteEpisodeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetEpisodeScriptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ScenarioScriptResponse
}

// Status returns HTTPResponse.Status
func (r GetEpisodeScriptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEpisodeScriptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetEpisodeScriptResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CompleteOnboardingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OnboardingCompleteResponse
}

// Status returns HTTPResponse.Status
func (r CompleteOnboardingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteOnboardingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CompleteOnboardingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SelectOnboardingFactionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r SelectOnboardingFactionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SelectOnboardingFactionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SelectOnboardingFactionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateOnboardingNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UpdateOnboardingNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateOnboardingNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateOnboardingNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetOnboardingScriptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OnboardingScriptResponse
}

// Status returns HTTPResponse.Status
func (r GetOnboardingScriptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOnboardingScriptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetOnboardingScriptResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListEpisodesWithResponse request returning *ListEpisodesResponse
func (c *ClientWithResponses) ListEpisodesWithResponse(ctx context.Context, params *ListEpisodesParams, reqEditors ...RequestEditorFn) (*ListEpisodesResponse, error) {
	rsp, err := c.ListEpisodes(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEpisodesResponse(rsp)
}

// CompleteEpisodeWithResponse request returning *CompleteEpisodeResponse
func (c *ClientWithResponses) CompleteEpisodeWithResponse(ctx context.Context, episodeId EpisodeIdPath, reqEditors ...RequestEditorFn) (*CompleteEpisodeResponse, error) {
	rsp, err := c.CompleteEpisode(ctx, episodeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteEpisodeResponse(rsp)
}

// GetEpisodeScriptWithResponse request returning *GetEpisodeScriptResponse
func (c *ClientWithResponses) GetEpisodeScriptWithResponse(ctx context.Context, episodeId EpisodeIdPath, params *GetEpisodeScriptParams, reqEditors ...RequestEditorFn) (*GetEpisodeScriptResponse, error) {
	rsp, err := c.GetEpisodeScript(ctx, episodeId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEpisodeScriptResponse(rsp)
}

// CompleteOnboardingWithResponse request returning *CompleteOnboardingResponse
func (c *ClientWithResponses) CompleteOnboardingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CompleteOnboardingResponse, error) {
	rsp, err := c.CompleteOnboarding(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteOnboardingResponse(rsp)
}

// SelectOnboardingFactionWithBodyWithResponse request with arbitrary body returning *SelectOnboardingFactionResponse
func (c *ClientWithResponses) SelectOnboardingFactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SelectOnboardingFactionResponse, error) {
	rsp, err := c.SelectOnboardingFactionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSelectOnboardingFactionResponse(rsp)
}

func (c *ClientWithResponses) SelectOnboardingFactionWithResponse(ctx context.Context, body SelectOnboardingFactionJSONRequestBody, reqEditors ...RequestEditorFn) (*SelectOnboardingFactionResponse, error) {
	rsp, err := c.SelectOnboardingFaction(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSelectOnboardingFactionResponse(rsp)
}

// UpdateOnboardingNameWithBodyWithResponse request with arbitrary body returning *UpdateOnboardingNameResponse
func (c *ClientWithResponses) UpdateOnboardingNameWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOnboardingNameResponse, error) {
	rsp, err := c.UpdateOnboardingNameWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateOnboardingNameResponse(rsp)
}

func (c *ClientWithResponses) UpdateOnboardingNameWithResponse(ctx context.Context, body UpdateOnboardingNameJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOnboardingNameResponse, error) {
	rsp, err := c.UpdateOnboardingName(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateOnboardingNameResponse(rsp)
}

// GetOnboardingScriptWithResponse request returning *GetOnboardingScriptResponse
func (c *ClientWithResponses) GetOnboardingScriptWithResponse(ctx context.Context, params *GetOnboardingScriptParams, reqEditors ...RequestEditorFn) (*GetOnboardingScriptResponse, error) {
	rsp, err := c.GetOnboardingScript(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOnboardingScriptResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseListEpisodesResponse parses an HTTP response from a ListEpisodesWithResponse call
func ParseListEpisodesResponse(rsp *http.Response) (*ListEpisodesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEpisodesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EpisodesListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCompleteEpisodeResponse parses an HTTP response from a CompleteEpisodeWithResponse call
func ParseCompleteEpisodeResponse(rsp *http.Response) (*CompleteEpisodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteEpisodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ScenarioCompleteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetEpisodeScriptResponse parses an HTTP response from a GetEpisodeScriptWithResponse call
func ParseGetEpisodeScriptResponse(rsp *http.Response) (*GetEpisodeScriptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEpisodeScriptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ScenarioScriptResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCompleteOnboardingResponse parses an HTTP response from a CompleteOnboardingWithResponse call
func ParseCompleteOnboardingResponse(rsp *http.Response) (*CompleteOnboardingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteOnboardingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OnboardingCompleteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSelectOnboardingFactionResponse parses an HTTP response from a SelectOnboardingFactionWithResponse call
func ParseSelectOnboardingFactionResponse(rsp *http.Response) (*SelectOnboardingFactionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SelectOnboardingFactionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUpdateOnboardingNameResponse parses an HTTP response from a UpdateOnboardingNameWithResponse call
func ParseUpdateOnboardingNameResponse(rsp *http.Response) (*UpdateOnboardingNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateOnboardingNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetOnboardingScriptResponse parses an HTTP response from a GetOnboardingScriptWithResponse call
func ParseGetOnboardingScriptResponse(rsp *http.Response) (*GetOnboardingScriptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOnboardingScriptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OnboardingScriptResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
