package apiscenario

import "time"

// オンボーディング完了イベントの topic 名。
const TopicPlayerOnboarded = "player-onboarded"

// PlayerOnboardedEvent の EventType 値。
const EventTypePlayerOnboarded = "player_onboarded"

// PlayerOnboardedEvent is published by scenario when a player completes the
// onboarding scenario (one-shot per player). Subscribers:
//
//   - account: UPDATE account.players.display_name (+ marks onboarded status).
//
// Idempotency: subscribers MUST dedupe on EventID via their
// processed_events table. See ADR-021 for the end-to-end design.
type PlayerOnboardedEvent struct {
	// EventType is always EventTypePlayerOnboarded.
	EventType string `json:"event_type"`
	// EventID is a UUIDv4 generated by scenario. Idempotency key.
	EventID string `json:"event_id"`
	// Timestamp is the publisher's wall clock at enqueue time.
	Timestamp time.Time `json:"timestamp"`
	// PlayerID is the target of the onboarding update.
	PlayerID string `json:"player_id"`
	// DisplayName is the player-entered display name collected during onboarding.
	DisplayName string `json:"display_name"`
	// InitialFactionID is one of SelectableFactions (SHE / Tenki / Sugar / Tuners).
	InitialFactionID string `json:"initial_faction_id"`
}
