// Code generated by scripts/generate_types.py; DO NOT EDIT.

package apiscenario

import (
	"time"
)

// ScenarioEpisode represents a story episode definition.
type ScenarioEpisode struct {
	EpisodeID        string    `json:"episode_id" db:"episode_id"`
	Faction          *string   `json:"faction" db:"faction"`
	EpisodeNumber    int64     `json:"episode_number" db:"episode_number"`
	TitleJa          string    `json:"title_ja" db:"title_ja"`
	TitleEn          string    `json:"title_en" db:"title_en"`
	RequiredLevel    int64     `json:"required_level" db:"required_level"`
	RequiredFactions []string  `json:"required_factions" db:"required_factions"`
	RequiredEpisodes []string  `json:"required_episodes" db:"required_episodes"`
	ScriptPath       string    `json:"-" db:"script_path"`
	ThumbnailPath    *string   `json:"-" db:"thumbnail_path"`
	SortOrder        int64     `json:"sort_order" db:"sort_order"`
	IsActive         bool      `json:"-" db:"is_active"`
	CreatedAt        time.Time `json:"-" db:"created_at"`
}

// StoryUnlockContext holds pre-fetched data needed for unlock checks.
type StoryUnlockContext struct {
	PlayerLevel       int64
	OwnedFactions     map[string]bool
	CompletedEpisodes map[string]bool
}

// LockReason describes a single unmet unlock condition.
type LockReason struct {
	Type     string      `json:"type"`
	Required interface{} `json:"required"`
	Current  interface{} `json:"current,omitempty"`
}

// EpisodeWithStatus is the API response element for a single episode with unlock state.
type EpisodeWithStatus struct {
	EpisodeID     string       `json:"episode_id"`
	Faction       *string      `json:"faction"`
	EpisodeNumber int64        `json:"episode_number"`
	Title         string       `json:"title"`
	ThumbnailURL  *string      `json:"thumbnail_url"`
	IsUnlocked    bool         `json:"is_unlocked"`
	IsCompleted   bool         `json:"is_completed"`
	LockReasons   []LockReason `json:"lock_reasons"`
}

type ScenarioScriptResponse struct {
	EpisodeID string `json:"episode_id"`
	Script    string `json:"script"`
}

type ScenarioCompleteResponse struct {
	Message   string `json:"message"`
	EpisodeID string `json:"episode_id"`
}


// NewLockReasonLevel builds a LockReason for an unmet level requirement.
func NewLockReasonLevel(required, current int64) LockReason {
	return LockReason{Type: "level", Required: required, Current: current}
}

// NewLockReasonFaction builds a LockReason for a missing required faction.
func NewLockReasonFaction(faction string) LockReason {
	return LockReason{Type: "faction", Required: faction}
}

// NewLockReasonEpisode builds a LockReason for an uncompleted prerequisite episode.
func NewLockReasonEpisode(episodeID string) LockReason {
	return LockReason{Type: "episode", Required: episodeID}
}
